version: "3.9"

services:
  sampleapis:
    container_name: sampleapis
    build:
      context: .
      dockerfile: server/Dockerfile
    restart: unless-stopped
    ports:
      - "5555:5555"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sampleapis.rule=Host(`sampleapis.assimilate.be`)"
      - "traefik.http.routers.sampleapis.entrypoints=web,websecure"
      - "traefik.http.routers.sampleapis.tls=true"
      - "traefik.http.routers.sampleapis.tls.certresolver=production" # Ensure 'myresolver' matches your Traefik Let's Encrypt resolver name
    networks:
      - web

networks:
  web:
    external: 
      name: traefik_default
